version: '3'

networks:
  db-net:
  backend-net:
  frontend-net:


services:
  db:
    image: postgres:17-alpine
    expose:
      - "5433"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - postgres.env
    networks:
      - db-net

  backend:
    build: ./backend
    ports:
      - 8082:8082
    depends_on:
      - db
    networks:
      - db-net
      - backend-net

  frontend:
    build: ./frontend
    volumes:
      - frontend:/app/build
    ports:
      - 3001:3001
    environment:
      - VITE_PORT=3001
    depends_on:
      - backend
    networks:
      - frontend-net

  nginx:
    build: ./nginx
    volumes:
      - frontend:/var/www/frontend
    ports:
      - 83:83
    depends_on:
      - frontend
    networks:
      - backend-net
      - frontend-net

volumes:
  db-data:
  frontend:
